/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan3;

/**
 *
 * @author SMKTELKOM
 */
public class Latihan3 extends javax.swing.JFrame {

   
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bilangan1 = new javax.swing.JTextField();
        bilangan2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Btnkali = new javax.swing.JButton();
        Btntambah = new javax.swing.JButton();
        Btnbagi = new javax.swing.JButton();
        Btnkurang = new javax.swing.JButton();
        Hasil = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Kalkulator Sederhana");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 20, 230, 28);
        getContentPane().add(bilangan1);
        bilangan1.setBounds(172, 76, 145, 30);
        getContentPane().add(bilangan2);
        bilangan2.setBounds(172, 124, 145, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Operator");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(172, 180, 56, 17);

        Btnkali.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Btnkali.setText("x");
        Btnkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnkaliActionPerformed(evt);
            }
        });
        getContentPane().add(Btnkali);
        Btnkali.setBounds(84, 215, 45, 40);

        Btntambah.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Btntambah.setText("+");
        Btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtntambahActionPerformed(evt);
            }
        });
        getContentPane().add(Btntambah);
        Btntambah.setBounds(211, 215, 47, 40);

        Btnbagi.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Btnbagi.setText(":");
        Btnbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbagiActionPerformed(evt);
            }
        });
        getContentPane().add(Btnbagi);
        Btnbagi.setBounds(152, 215, 41, 40);

        Btnkurang.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Btnkurang.setText("-");
        Btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnkurangActionPerformed(evt);
            }
        });
        getContentPane().add(Btnkurang);
        Btnkurang.setBounds(276, 215, 41, 40);
        getContentPane().add(Hasil);
        Hasil.setBounds(152, 296, 106, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Hasil");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(186, 273, 31, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Bilangan 2");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 130, 80, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Bilangan 1");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 80, 80, 17);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 380);

        setBounds(0, 0, 416, 394);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnkurangActionPerformed
        // TODO add your handling code here:
        double bil1 = Double.parseDouble(bilangan1.getText());
        double bil2 = Double.parseDouble(bilangan2.getText());
        double hasil = bil1-bil2;
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_BtnkurangActionPerformed

    private void BtnbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbagiActionPerformed
        // TODO add your handling code here:
        double bil1 = Double.parseDouble(bilangan1.getText());
        double bil2 = Double.parseDouble(bilangan2.getText());
        double hasil4 = bil1/bil2;
        Hasil.setText(String.valueOf(hasil4));   
    }//GEN-LAST:event_BtnbagiActionPerformed

    private void BtnkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnkaliActionPerformed
        // TODO add your handling code here:
        double bil1 = Double.parseDouble(bilangan1.getText());
        double bil2 = Double.parseDouble(bilangan2.getText());
        double hasil2 = bil1*bil2;
        Hasil.setText(String.valueOf(hasil2));
    
    }//GEN-LAST:event_BtnkaliActionPerformed

    private void BtntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtntambahActionPerformed
        // TODO add your handling code here:
        double bil1 = Double.parseDouble(bilangan1.getText());
        double bil2 = Double.parseDouble(bilangan2.getText());
        double hasil3 = bil1+bil2;
        Hasil.setText(String.valueOf(hasil3));
        
    }//GEN-LAST:event_BtntambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnbagi;
    private javax.swing.JButton Btnkali;
    private javax.swing.JButton Btnkurang;
    private javax.swing.JButton Btntambah;
    private javax.swing.JTextField Hasil;
    private javax.swing.JTextField bilangan1;
    private javax.swing.JTextField bilangan2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
